# Generated by Django 2.1.7 on 2019-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMonthlyProgressObjectBased',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gs_no', models.TextField(blank=True, null=True)),
                ('financial_month', models.TextField(blank=True, null=True)),
                ('financial_year', models.TextField(blank=True, null=True)),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('object_code', models.TextField(blank=True, null=True)),
                ('object_code_title', models.TextField(blank=True, null=True)),
                ('provision_total', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('provision_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('provision_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('revised_allocation_total', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('revised_allocation_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('revised_allocation_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pnd_released_total', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pnd_released_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pnd_released_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fd_released_total', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fd_released_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fd_released_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('received_released_total', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('received_released_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('received_released_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('utilized', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('percentage_util_revised_allocation', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('user', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='tblconsultancydata',
            options={'managed': False},
        ),
    ]
